### ISSUE TITLE
Fix Python classifiers

### ISSUE THREAD

**Issue by adrien-berchet** [bgeron/diff-pdf-visually#7]
Hi @bgeron 
I have an issue with the last release: it only works with py38+ but the classifiers in the setup.py still states it is supposed to work on py36+, so pip is still installing it for py36 and py37 while it should not. The setup.py seems to be generated by hatch but I never used it so I would prefer you update it yourself. But I can try if you have no time for this.

**Comment by bgeron** [comment]
Hi Adrien! Thanks for reporting this.

I had removed `3.6` and `3.7` from the list of advertised supported versions because I can't test them any more with `tox` on my Ubuntu desktop. But I hadn't realized that that would be a breaking change for some :grimacing: Turns out I can configure the two separately, so all is good. I just restored advertised compatibility with py36 and py37, and released `v1.6.1` of `diff-pdf-visually`.

Unfortunately I can't guarantee that it keeps working, because it's getting harder to test... But please let me know if it breaks in practice.

I'm guessing that this fixes it for you so I'll close it, but please reopen if it doesn't.

Cheers, Bram
